[phases.setup]
nixPkgs = ["...", "jdk17"]

[phases.build]
cmds = [
  "cd backend",
  "./mvnw clean package -DskipTests"
]

[start]
cmd = "cd backend && java -jar target/elegantevents-backend-1.0.0.jar"
